nav:
 - 'Overview': index.md
 - 'Get Started': get-started.md
 - 'Create a Bucket': create-a-bucket.md
 - 'Issue a Storage Request': issue-a-storage-request.md
 - 'Verify Storage Request Registration': verify-storage-request-registration.md
 - 'Upload Your First File': upload-your-first-file.md
 - 'Retrieve Your Data': retrieve-your-data.md
 - 'End-to-End StorageHub SDK Workflow': end-to-end-storage-workflow.md
 - 'Authenticate with SIWE and JWT': authenticate-with-siwe-and-jwt.md
 - 'FAQs and Troubleshooting': faqs-and-troubleshooting.md

