nav:
 - 'Get Started': get-started.md
 - 'Create a Bucket': create-a-bucket.md
 - 'Authenticate with SIWE and JWT': authenticate-with-siwe-and-jwt.md
 - 'File Manipulation': file-manipulation.md
 - 'Upload a File': upload-a-file.md
 - 'Retrieve Your Data': retrieve-your-data.md
 - 'End-to-End Storage Workflow': end-to-end-storage-workflow.md
 - 'Manage Files and Buckets': manage-files-and-buckets.md
 - 'Set Custom Gas Params': set-custom-gas-params.md
 - 'Resolve Insolvent Status via API': resolve-insolvent-status-via-api.md
 - 'Resolve Insolvent Status via UI': resolve-insolvent-status-via-ui.md
 - 'FAQs & Troubleshooting': faqs-and-troubleshooting.md
 