nav:
 - 'Overview': index.md
 - 'Network Details': network-details
 - 'Spin up Local Devnet': spin-up-local-devnet.md
 - 'Use the DataHaven dApp': use-the-datahaven-dapp.md
 - 'Use StorageHub SDK': use-storagehub-sdk
 - 'Manage and Optimize Your Data': manage-and-optimize-your-data
