nav:
 - 'Get Started': get-started.md
 - 'Run a BSP Node': run-a-bsp-node.md
 - 'Verify BSP Node': verify-bsp-node.md
 - 'End-to-End BSP Onboarding': end-to-end-bsp-onboarding.md
#  - 'Deregister BSP Node': deregister-bsp-node.md
 - 'BSP CLI Flags': bsp-cli-flags.md
 - 'BSP Troubleshooting': bsp-troubleshooting.md